name : Update Content Statistics

on:
    workflow_dispatch:
        
    # push:
    #     branches:
    #         - main
    #     paths:
    #         -   content/**
    #         -   .github/workflows/Statistics/Tracked.js

jobs:
    Update_Statistics:
        runs-on : ubuntu-latest
        steps:
            
            -   uses : denoland/setup-deno@v1
                with :
                    deno-version : 1.23.4
                    
            -   uses : actions/checkout@v3
                with :
                    repository: ${{ github.event.pull_request.head.repo.full_name }}
                    ref: ${{ github.event.pull_request.head.ref }}
                
            -   name : Run Statistics Updater
                run : 'deno run 
                    --allow-read 
                    --allow-write 
                    --importmap=.github/workflows/Statistics/Imports.json 
                    .github/workflows/Statistics/.js'
                    
            -   name : Commit generated README
                uses : EndBug/add-and-commit@v9
                with:
                    default_author : github_actor
                    message : 'Updated Content Statistics'
                    add: '.github/Statistics.yaml'
